rvm:
 - 1.9.3
 - 2.0.0
 - 2.1.0
 - jruby-18mode
 - jruby-19mode
 - ruby-head
 - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode
script:
  bundle exec rake full_test

